[features]
seeds = false
skip-lint = false
[programs.mainnet]
spl_staking = "GaJ7t7cq1oqVbpE5bBd7ptzuHHyFRjGZmjiZuFojAsgE"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
